Com 3436
CompaniTech/compani-api pull request #2222
Opened 2023-04-12 15:25 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [ ] J'ai codé les tests unitaires -np
- [ ] J'ai codé les tests d'intégration -np
- [ ] ~~C'est une ancienne route utilisée par les apps mobiles.~~
  - [ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [ ] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)
- [ ] J'ai ajouté un modèle spécifique à une structure 
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [x] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [ ] Mes changements impactent l'application formation
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] Mes changements impactent l'application erp
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [x] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-04-17 08:05 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if every published subProgram has at leat one step', async () => {
least

2023-04-17 08:48 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +          const someAccessRulesAreDuplicate = coursesWithAccessRules
done

2023-04-17 08:48 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +        it('should pass if every published subProgram has at leat one step', async () => {
done

2023-04-17 08:59 UTC, cmolle approved these changes

2023-04-17 09:10 UTC, cmolle commented on tests/integration/seed/seedsVerification.test.js
> +        });
On pourrait peut etre le fusionner avec celui plus haut qui verifie qu'on a pas deux fois le meme sous-programme dans un meme programme qu'en penses-tu ? Si celui plus haut casse, celui-ci casse aussi.

2023-04-17 09:20 UTC, ulysseferreira commented on tests/integration/seed/seedsVerification.test.js
> +        });
done

2023-04-17 14:00 UTC, sophiemoustard requested changes

2023-04-17 14:15 UTC, ulysseferreira commented on tests/integration/seed/coursesSeed.js
> -    misc: 'inter b2c session NOT concerning auth company',
c'est une inter_b2c (strictly_e-learning), il n'y a pas de misc dans ces cas là

2023-04-18 07:11 UTC, sophiemoustard approved these changes

2023-04-18 07:11 UTC, merged