Com 3461
CompaniTech/compani-api pull request #2235
Opened 2023-05-25 12:32 UTC by ulysseferreira

<details open><summary> TESTS  :computer: </summary>

- [x] J'ai codé les tests unitaires
- [x] J'ai codé les tests d'intégration
- [x] C'est une ancienne route utilisée par les apps mobiles.
  - [x] Si oui, J'ai fait de nouveaux tests sans modifier les anciens
</details>

- [ ] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration

---

<details open><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>

- [x] J'ai fait des modifications sur une route utilisée sur plusieurs plateformes [Doc de détail](https://www.notion.so/Points-d-attention-sur-les-routes-a548a8e32d314d5e92cb342e66cce443)
- [ ] ~~J'ai modifié un modèle utilisé en mobile [Doc de détail](https://www.notion.so/Point-d-attention-sur-les-mod-les-e46fbf180cd34a569f3c6102366e47ca)~~
- [ ] ~~J'ai ajouté un modèle spécifique à une structure~~
  - [ ] Si oui, j'ai ajouté le champs company ainsi que les prehooks associés
- [ ] ~~J'ai ajouté/modifié une constante qui est utilisée sur les apps mobile~~
  - [ ] Si oui, j'ai précisé sur le [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) qu'il faut forcer la mise à jour
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

</details>

- [ ] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention

---

<details open><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>

- [x] Mes changements impactent l'application formation
  - [x] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours
- [ ] ~~Mes changements impactent l'application erp~~
  - [ ] Si oui, j'ai testé que les anciennes versions maintenues fonctionnent toujours

</details>

- [ ] Je replie cette section car mes modifications n'ont pas d'impact sur les applications mobiles

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-05-25 13:57 UTC, cmolle commented on src/controllers/holdingController.js
> +    return { message: translate[language].companyLinkedToHolding };
Que penses-tu de plutôt renvoyé un message `holdingUpdated` ? Je pense qu'on utilisera la meme route pour modifier d'autres infos de la holding (nom et adresse)

2023-05-25 13:57 UTC, cmolle commented on src/helpers/companies.js
> +      .find({}, { _id: 1, company: 1 })
Tu peux recuperer uniquement company directement, comme ca pas besoin du map plus bas (il faut mettre `_id: 0` pour forcer le fait de ne pas prendre l'id)

2023-05-25 13:57 UTC, cmolle commented on src/helpers/companies.js
> +exports.list = async (hasHolding = false) => {
le `hasHolding` me perturbe un peu, vu qu'on recupere justement les entreprises qui n'ont pas de holding. Que penses-tu de plutot `noHoldingCompany` ?

2023-05-25 13:57 UTC, cmolle commented on src/helpers/companies.js
> +  return Company.find({ _id: { $nin: linkedCompanyList.flat() } }, { _id: 1, name: 1 }).lean();
l'_id est recupere par defaut, tu n'es pas oblige de le preciser

2023-05-25 13:57 UTC, cmolle commented on src/routes/holdings.js
> +          }).required(),
Sur une ligne ?

2023-05-25 13:57 UTC, cmolle commented on src/helpers/companies.js
> +      .setOptions({ allCompanies: true })
Qu'est-ce qui t'a fait choisir cette option ? (notamment par rapport a `isVendorUser` ?

2023-05-25 14:58 UTC, ulysseferreira commented on src/controllers/holdingController.js
> +    return { message: translate[language].companyLinkedToHolding };
done

2023-05-25 15:01 UTC, ulysseferreira commented on src/helpers/companies.js
> +      .find({}, { _id: 1, company: 1 })
ça me retire id mais j'ai quand même des objets, non ? j'ai [{company: ObjectId}, {company: ObjectId}] mais je veux [ObjectId, ObjectId]

2023-05-25 15:05 UTC, ulysseferreira commented on src/helpers/companies.js
> +exports.list = async (hasHolding = false) => {
j'ai mis noHolding

2023-05-25 15:06 UTC, ulysseferreira commented on src/helpers/companies.js
> +  return Company.find({ _id: { $nin: linkedCompanyList.flat() } }, { _id: 1, name: 1 }).lean();
done

2023-05-25 15:06 UTC, ulysseferreira commented on src/routes/holdings.js
> +          }).required(),
done

2023-05-25 15:09 UTC, ulysseferreira commented on src/helpers/companies.js
> +      .setOptions({ allCompanies: true })
parce que c'est une route que tout le monde peut appeler, et en soit là la restriction est, certes faites par les vendeurs dans les faits, mais y a pas de point critique à ce que n'importe qui la fasse, si un simple utilisateur appelle cette route avec noHolding, je ne vois pas le soucis de lui renvoyer la liste. tu en penses quoi ?

2023-05-25 15:50 UTC, ulysseferreira commented on src/controllers/companyController.js
> +    const companies = await CompanyHelper.list(req.query.hasHolding);
done

2023-05-26 07:16 UTC, cmolle commented on src/helpers/companies.js
> +      .find({}, { _id: 1, company: 1 })
Ha oui tu as raison !

2023-05-26 07:28 UTC, cmolle commented on src/helpers/translate.js
> +    holdingFound: 'Société mère trouvée.',
On a toujours la version pluriel et singulier ? On pourrait avoir Société(s) mère(s) trouvée(s) pour éviter d'avoir deux textes différents 🤔 Sinon on peut peut etre mettre `holdingListFound` pour que l'on voit mieux la différence du premier coup d'oeil. Qu'en penses-tu ?

2023-05-26 07:28 UTC, cmolle commented on src/helpers/companies.js
> +      .setOptions({ allCompanies: true })
C'est vrai que les utilisateurs ont le droit de connaitre les entreprises du coup ils pourraient avoir acces aux holding aussi 🤔 Est-ce que du coup il y a besoin de mettre les prehooks sur le modele companyHolding ? J'ai l'impression qu'on va devoir mettre `allCompanies` partout ou on utilisera le modele companyHolding.

2023-05-26 08:06 UTC, ulysseferreira commented on src/helpers/translate.js
> +    holdingFound: 'Société mère trouvée.',
ça me va

2023-05-26 08:06 UTC, ulysseferreira commented on src/helpers/companies.js
> +      .setOptions({ allCompanies: true })
je l'ai retiré

2023-05-26 08:51 UTC, sophiemoustard commented on src/helpers/companies.js
> +exports.list = async (hasHolding = false) => {
je trouve que les doubles negation sont toujours un peu perturbante.. si on parle de "un structure sans société mère" je trouve ca plus logique d'envoyer `false` dans la requete que `true`

2023-05-26 09:09 UTC, cmolle approved these changes

2023-05-26 11:47 UTC, sophiemoustard requested changes

2023-05-26 11:47 UTC, sophiemoustard commented on src/helpers/companies.js
> +    linkedCompanyList.push(companyHoldings.map(ch => ch.company));
pourquoi tu `push` t tu ne fias pas simplement `linkedCompanyList = companyHoldings.map(ch => ch.company)` ?

2023-05-26 11:47 UTC, sophiemoustard commented on src/routes/holdings.js
> +          payload: Joi.object().keys({ company: Joi.objectId() }).required(),
c'est etrange ce `required` sur le `payload`

2023-05-26 11:47 UTC, sophiemoustard commented on src/routes/preHandlers/holdings.js
> +  if (!company) throw Boom.notFound();
avoir une condition `if (payload.company)` serait pas mal je pense

2023-05-26 11:47 UTC, sophiemoustard commented on src/routes/preHandlers/holdings.js
> +  if (companyHolding) throw Boom.forbidden();
pareil pour ca

2023-05-26 11:47 UTC, sophiemoustard commented on src/routes/preHandlers/holdings.js
> +  const holding = await Holding.countDocuments({ _id: req.params._id });
je trouverai ca plus loogique de faire cette etape en premier

2023-05-26 11:47 UTC, sophiemoustard commented on tests/integration/holdings.test.js
> +      expect(companyHoldingsCount).toEqual(companyHoldingsBefore + 1);
tu pourrais enrichir ta verification en regardant si le nombre de `companyHolding` rattachée a cette holding a bien augmenté de 1

2023-05-26 11:47 UTC, sophiemoustard commented on src/routes/preHandlers/holdings.js
> +  if (!company) throw Boom.notFound();
ou alors si tu le considère comme toujours présent, met le en requis dans la route

2023-05-26 11:47 UTC, sophiemoustard commented on src/helpers/holdings.js
> +exports.update = async (holdingId, payload) => CompanyHolding.create({ holding: holdingId, company: payload.company });
ici tu peux mettre une condition sur la presence de `company` dans le payload

2023-05-26 11:47 UTC, sophiemoustard commented on src/models/Holding.js
> +HoldingSchema.virtual('companyHoldingList', { ref: 'CompanyHolding', localField: '_id', foreignField: 'holding' });
tu pourrais l'appeler `companyHoldings` non ?

2023-05-26 12:21 UTC, ulysseferreira commented on src/helpers/companies.js
> +    linkedCompanyList.push(companyHoldings.map(ch => ch.company));
done mais ça fait passer linkedCompanyList en variable (let), il me semblait que d'habitude on utilisati plus des constantes dans lesquelles on pushait

2023-05-26 12:22 UTC, ulysseferreira commented on src/routes/holdings.js
> +          payload: Joi.object().keys({ company: Joi.objectId() }).required(),
done

2023-05-26 12:23 UTC, ulysseferreira commented on src/routes/preHandlers/holdings.js
> +  if (!company) throw Boom.notFound();
il ne sera sans doute pas toujours présent à l'avenir quand on modifiera la holding, j'ai mis le if

2023-05-26 12:24 UTC, ulysseferreira commented on src/routes/preHandlers/holdings.js
> +  const holding = await Holding.countDocuments({ _id: req.params._id });
done

2023-05-26 12:25 UTC, ulysseferreira commented on tests/integration/holdings.test.js
> +      expect(companyHoldingsCount).toEqual(companyHoldingsBefore + 1);
done

2023-05-26 12:26 UTC, ulysseferreira commented on src/helpers/holdings.js
> +exports.update = async (holdingId, payload) => CompanyHolding.create({ holding: holdingId, company: payload.company });
done

2023-05-26 12:27 UTC, ulysseferreira commented on src/models/Holding.js
> +HoldingSchema.virtual('companyHoldingList', { ref: 'CompanyHolding', localField: '_id', foreignField: 'holding' });
done

2023-05-26 12:57 UTC, sophiemoustard approved these changes

2023-05-26 14:57 UTC, merged